zmieszane:
  output: /config/scripts/smieci-zmieszane.json
  bymonth:
    1: [ 4, 18 ]
    2: [ 1, 15 ]
    3: [ 1, 15, 29 ]
    4: [ 12, 26 ]
    5: [ 10, 24 ]
    6: [ 7, 21 ]
    7: [ 5, 19 ]
    8: [ 2, 16, 30 ]
    9: [ 13, 27 ]
    10: [ 11, 25 ]
    11: [ 8, 22 ]
    12: [ 6, 20 ]

segregowane-zolte:
  output2: /config/scripts/smieci-segregowane-zolte.json
  output4: smieci-segregowane-zolte.json
  output3: "-"
  bymonth:
    1: [ 12, 26 ]
    2: [ 9, 23 ]
    3: [ 9, 23 ]
    4: [ 6, 20 ]
    5: [ 4, 18 ]
    6: [ 15, 29 ]
    7: [ 13, 27 ]
    8: [ 10, 24 ]
    9: [ 7, 21 ]
    10: [ 5, 19 ]
    11: [ 16, 30 ]
    12: [ 14, 28 ]
